#!/usr/bin/env bash
#
# Provision an Ubuntu 24.04 host to serve The-abyss.
#
# This is the server-side mirror of docker/Dockerfile and docker/entrypoint.sh.
# The container was built by hand, one step at a time, so that this script could
# be written from something already proven rather than from a guess. Where the
# two differ, the difference is deliberate and commented.
#
# Provider-neutral, as of 2026-08-02. Everything between here and the "Done"
# banner targets Ubuntu, not a provider, and has been verified to run unchanged
# on a bare ubuntu:24.04 image twice in a row. Hosting is still undecided in
# PLAN.md, and this script had already been retargeted three times in four days,
# each retarget editing prose rather than code. So the provider-specific parts
# are now confined to one block, at the bottom, under "Remaining".
#
#   # ON SERVER
#   sudo SITE_DOMAIN=example.com SITE_TITLE='The-abyss' \
#        ADMIN_USER=casey ADMIN_EMAIL=you@example.com \
#        bash scripts/provision.sh
#
# `sudo` because a DigitalOcean droplet logs in as root while an EC2 Ubuntu AMI
# logs in as `ubuntu` with root SSH disabled. Under sudo both work; as root only
# one does.
#
# Passwords are never arguments, never defaults, and never written to this file.
# The script prompts for them with a silent read, so they stay out of the shell
# history, out of the process list, and out of the repository. That is tier 0 in
# AGENTS.md and the reason wp-config.php is not generated by the container
# entrypoint either.
#
# Idempotent: safe to re-run. Every step checks for its own result first, so a
# re-run after a failure resumes rather than duplicating.

set -euo pipefail

SKIPS=0

# --- configuration ----------------------------------------------------------

SITE_DOMAIN="${SITE_DOMAIN:-}"
SITE_TITLE="${SITE_TITLE:-The-abyss}"
ADMIN_USER="${ADMIN_USER:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-}"

WP_DIR="/var/www/the-abyss"
DB_NAME="${DB_NAME:-theabyss}"
DB_USER="${DB_USER:-theabyss}"

# The repository, so the theme can be deployed from it. Defaults to the checkout
# this script is being run from.
REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

log()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

# Is this a real host with an init system, or a container?
#
# The script has to run in both. A plain container has no systemd, no ufw that
# can load kernel modules, and no swap it is allowed to create, and PLAN.md
# already records that as the container's known limitation. Guarding these three
# is what lets the whole WordPress-shaped part of this script be tested in a
# throwaway container before it is ever pointed at a paid instance that costs
# money and takes a rebuild to fix.
#
# The guards skip; they never fake. A skipped step says so, loudly, so a
# container run is never mistaken for a full one.
has_systemd() { [ -d /run/systemd/system ]; }

# Start or restart a service through whichever mechanism exists.
svc() {
	if has_systemd; then
		systemctl "$1" "$2"
	else
		service "$2" "$1" >/dev/null 2>&1 || true
	fi
}
warn() { printf '\033[33mwarning: %s\033[0m\n' "$*" >&2; }
skipped() { printf '\033[33m   SKIPPED — %s\033[0m\n' "$*"; SKIPS=$((SKIPS+1)); }
die()  { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root: sudo bash scripts/provision.sh"
[ -n "$SITE_DOMAIN" ] || die "SITE_DOMAIN is required, for example SITE_DOMAIN=example.com"
[ -n "$ADMIN_USER" ]  || die "ADMIN_USER is required."
[ -n "$ADMIN_EMAIL" ] || die "ADMIN_EMAIL is required."

# --- guard: do not clobber a site this script does not own -------------------
#
# This host has previously shared space with a live portfolio site. A provisioning
# script that silently disables another vhost, or overwrites another site's
# document root, is the single most damaging thing in this file. So it refuses
# rather than assumes.

if [ -e "$WP_DIR" ] && [ ! -e "$WP_DIR/wp-includes/version.php" ]; then
	die "$WP_DIR exists but is not a WordPress install. Refusing to touch it."
fi

for conf in /etc/apache2/sites-enabled/*.conf; do
	[ -e "$conf" ] || continue
	case "$(basename "$conf")" in
		the-abyss.conf|000-default.conf) continue ;;
	esac
	warn "another enabled vhost is present: $(basename "$conf")"
	warn "this script only adds the-abyss.conf and never disables anything else."
done

# --- packages ---------------------------------------------------------------
#
# The same list the Dockerfile installs. The PHP extensions are separate Debian
# packages, and a missing one surfaces as a blank 500 with nothing in the error
# log, because WordPress calls wp_die() rather than raising a PHP error. That
# cost a debugging session in the container; it is spelled out here so it cannot
# cost another one on the server.

log "Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq --no-install-recommends \
	ca-certificates curl less nano \
	apache2 \
	php-fpm php-mysql php-curl php-xml php-mbstring php-zip php-gd php-intl \
	mysql-server \
	certbot python3-certbot-apache \
	fail2ban \
	ufw

# --- apache -----------------------------------------------------------------

log "Configuring Apache"

# The FPM conf name carries the PHP version, which differs between Ubuntu
# releases. Discovering it is what keeps this script working across an upgrade.
FPM_CONF="$(basename "$(ls /etc/apache2/conf-available/php*-fpm.conf | head -n1)" .conf)"
[ -n "$FPM_CONF" ] || die "no php*-fpm.conf found; is php-fpm installed?"

a2enmod proxy_fcgi setenvif rewrite headers >/dev/null
a2enconf "$FPM_CONF" >/dev/null

# The vhost is the same file the container uses, with only ServerName changed —
# which is exactly the claim docker/the-abyss.conf makes about itself. Copying
# and substituting keeps that claim true instead of aspirational.
# Owned by www-data from the moment it exists. Found by the container test on
# 2026-08-01: created as root, the later `wp core download` runs as www-data and
# dies with "'/var/www/the-abyss/' is not writable by current user". The chown
# further down came after the download, which is too late to help.
install -d -o www-data -g www-data "$WP_DIR"
sed "s/ServerName localhost/ServerName $SITE_DOMAIN\n    ServerAlias www.$SITE_DOMAIN/" \
	"$REPO_DIR/docker/the-abyss.conf" > /etc/apache2/sites-available/the-abyss.conf

a2ensite the-abyss >/dev/null
# 000-default answers on the same *:80 with no ServerName, so whichever loaded
# first wins and the Apache welcome page shows instead of the site.
a2dissite 000-default >/dev/null 2>&1 || true
apache2ctl configtest
svc reload apache2
svc start apache2

# --- wp-cli -----------------------------------------------------------------
#
# Official phar, not the Debian package, which lags badly. Same two lines as the
# Dockerfile.

if ! command -v wp >/dev/null; then
	log "Installing WP-CLI"
	curl -fsSL -o /usr/local/bin/wp \
		https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
	chmod +x /usr/local/bin/wp
	wp --allow-root --info >/dev/null
fi

# www-data's home is /var/www, which it does not own, so WP-CLI cannot create its
# cache and prints "Failed to create directory '/var/www/.wp-cli/cache/'" on
# every call. Creating it with the right owner silences that at the source rather
# than by redirecting warnings away.
install -d -o www-data -g www-data /var/www/.wp-cli/cache
wp_run() { sudo -u www-data -- wp --path="$WP_DIR" "$@"; }

# --- database ---------------------------------------------------------------

log "Database"

# Started explicitly rather than assumed. On any host with systemd both are
# started at install time, so this is a no-op there; in a container nothing
# starts them and every
# mysql call below would fail with a socket error that reads like a permissions
# problem. Being explicit costs nothing and removes a whole class of confusing
# first-run failure.
svc start mysql
svc start "$FPM_CONF"
sleep 2

# Container only. systemd-tmpfiles normally creates /run/mysqld as 0755, and
# without it mysqld's own startup leaves the directory 0700 mysql:mysql. The
# socket inside is world-writable, but www-data cannot traverse the directory to
# reach it, so WordPress reports "Error establishing a database connection"
# while the identical credentials work from a root shell. Guarded to no-systemd
# hosts so it never touches permissions systemd owns on a real server.
if ! has_systemd && [ -d /run/mysqld ]; then
	chmod 0755 /run/mysqld
fi

if mysql -N -B -e "SHOW DATABASES LIKE '$DB_NAME';" | grep -q "$DB_NAME"; then
	echo "database $DB_NAME already exists, leaving it alone"
	DB_PASS=""
else
	# Silent read. Never a script default, never an argument, so it stays out of
	# the process list and the shell history.
	read -rsp "New password for MySQL user '$DB_USER': " DB_PASS; echo
	[ -n "$DB_PASS" ] || die "database password cannot be empty."

	# utf8mb4 so emoji and non-Latin scripts survive. utf8 in MySQL is three
	# bytes and silently truncates at the first four-byte character.
	mysql -e "CREATE DATABASE \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
	mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
	mysql -e "GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';"
	mysql -e "FLUSH PRIVILEGES;"
fi

# --- wordpress core ---------------------------------------------------------

log "WordPress core"

if [ ! -f "$WP_DIR/wp-includes/version.php" ]; then
	sudo -u www-data -- wp --path="$WP_DIR" core download
fi
chown -R www-data:www-data "$WP_DIR"

if [ ! -f "$WP_DIR/wp-config.php" ]; then
	[ -n "$DB_PASS" ] || die "wp-config.php is missing but the database already existed, so its password is not known here. Write wp-config.php by hand, or drop the database and re-run."

	# Salts come from the WordPress.org API, which wp config create calls itself.
	wp_run config create \
		--dbname="$DB_NAME" --dbuser="$DB_USER" --dbpass="$DB_PASS" \
		--dbcharset=utf8mb4 --dbcollate=utf8mb4_unicode_ci --skip-check

	# Pinned by constant rather than left in the database, so the site cannot be
	# half-migrated by an option row someone forgot. The container does the same
	# against http://localhost:8080.
	wp_run config set WP_HOME    "https://$SITE_DOMAIN" --type=constant
	wp_run config set WP_SITEURL "https://$SITE_DOMAIN" --type=constant

	# File edit from wp-admin is a code-execution path for any compromised admin
	# account, and this theme is deployed from Git rather than edited in place.
	wp_run config set DISALLOW_FILE_EDIT true --raw --type=constant
fi
unset DB_PASS

if ! wp_run core is-installed 2>/dev/null; then
	read -rsp "Password for the new WordPress admin '$ADMIN_USER': " ADMIN_PASS; echo
	[ -n "$ADMIN_PASS" ] || die "admin password cannot be empty."

	wp_run core install \
		--url="https://$SITE_DOMAIN" \
		--title="$SITE_TITLE" \
		--admin_user="$ADMIN_USER" \
		--admin_password="$ADMIN_PASS" \
		--admin_email="$ADMIN_EMAIL" \
		--skip-email
	unset ADMIN_PASS
fi

# Pretty permalinks. Requires AllowOverride All, which the vhost already sets;
# without it every URL except the home page 404s.
#
# Flat, not '/%category%/%postname%/'. A category in the path means a post's URL
# changes whenever it is recategorised, and a post in two categories gets one of
# them picked for it. The topical grouping that structure buys is carried by
# breadcrumbs and internal links instead, neither of which breaks a live URL.
wp_run rewrite structure '/%postname%/' >/dev/null
wp_run rewrite flush --hard >/dev/null

# `wp rewrite flush --hard` writes the BEGIN/END WordPress markers but leaves
# them empty when it cannot detect Apache, which it cannot from the CLI. The
# result is a site where every URL except the home page 404s, with an .htaccess
# that looks correct at a glance because the markers are there. Observed locally
# 2026-08-01. Written explicitly rather than trusted.
if ! grep -q 'RewriteEngine On' "$WP_DIR/.htaccess" 2>/dev/null; then
	cat > "$WP_DIR/.htaccess" <<'HTACCESS'

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
HTACCESS
	chown www-data:www-data "$WP_DIR/.htaccess"
fi

# --- theme ------------------------------------------------------------------
#
# Deployed by symlink from the checkout, matching the container, so a git pull is
# the whole deploy and there is no copy step to forget.

log "Theme"
THEMES_DIR="$WP_DIR/wp-content/themes"
# Renamed 2026-08-01: the theme directory is abyss-theme, and the old `theme/`
# was deleted in the same change. Left as `the-abyss` this silently created a
# dangling symlink and then failed to activate a theme that no longer exists.
if [ ! -e "$THEMES_DIR/abyss-theme" ]; then
	ln -s "$REPO_DIR/abyss-theme" "$THEMES_DIR/abyss-theme"
fi
wp_run theme activate abyss-theme

# --- plugins ----------------------------------------------------------------
#
# Read from scripts/plugins.txt so this list exists in exactly one place.

log "Plugins"
# Read on fd 3, not stdin. `wp` inherits stdin and will happily consume the rest
# of the plugin list, so a plain `while read ... done < file` installs the first
# plugin and silently skips the others.
while read -r line <&3; do
	line="${line%%#*}"
	line="$(echo "$line" | xargs || true)"
	[ -n "$line" ] || continue

	slug="${line%%:*}"
	if [ "$line" = "${slug}:inactive" ]; then
		wp_run plugin is-installed "$slug" 2>/dev/null || wp_run plugin install "$slug"
	else
		wp_run plugin is-installed "$slug" 2>/dev/null || wp_run plugin install "$slug"
		wp_run plugin activate "$slug" >/dev/null
	fi
done 3< "$REPO_DIR/scripts/plugins.txt"

# --- hardening --------------------------------------------------------------

log "Swap"
# Neither EC2 nor the smaller droplet sizes ship with swap. The architecture
# table in PLAN.md calls for 2 GiB at low swappiness: MySQL, PHP workers, and
# image processing sharing 2 GiB of RAM is exactly where a WordPress host OOMs,
# and the OOM killer usually takes MySQL, which looks like data corruption
# rather than memory pressure.
if ! has_systemd; then
	skipped "swap: containers cannot swapon; this runs on the real host only"
elif [ "$(swapon --show --noheadings | wc -l)" -eq 0 ] && [ ! -f /swapfile ]; then
	fallocate -l 2G /swapfile
	chmod 600 /swapfile
	mkswap /swapfile >/dev/null
	swapon /swapfile
	grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
	# Low, not zero. Swapping is a last resort here, not routine paging.
	sysctl -q -w vm.swappiness=10
	grep -q '^vm.swappiness' /etc/sysctl.conf || echo 'vm.swappiness=10' >> /etc/sysctl.conf
else
	echo "swap already present, leaving it alone"
fi

log "Firewall and fail2ban"
# ufw is the host-level layer, and on some providers it is the only layer. An
# EC2 security group always sits in front of it; a DigitalOcean cloud firewall
# does only if one has been attached, and by default none is. Either way the two
# can disagree silently — a port opened in the provider's console and closed here
# simply does not work, with nothing in either place saying why. Check both when
# a port appears dead.
#
# OpenSSH is allowed before enabling, which is the difference between a firewall
# and a lockout. Recovering from a lockout means the provider's console recovery
# path, so the ordering here is load-bearing on every provider.
if has_systemd; then
	ufw allow OpenSSH >/dev/null
	ufw allow 'Apache Full' >/dev/null
	ufw --force enable >/dev/null
	systemctl enable --now fail2ban >/dev/null
else
	skipped "firewall and fail2ban: no init system; this runs on the real host only"
fi

# --- TLS --------------------------------------------------------------------
#
# Deliberately last, and deliberately not run. Certbot fails and burns a rate
# limit if DNS does not already resolve to this host, and pointing DNS is an
# outward-facing action that belongs to the human, not to a script.

log "Done"
cat <<EOF

Provisioned: https://$SITE_DOMAIN  (not yet TLS)

Remaining, in order, and yours to run. Everything above this line was
provider-neutral; everything below is where the two differ.

  1. Make sure this host has a stable public IP. Both DNS and TLS need one.
       droplet — it already has one. A Reserved IP is optional, and only
                 buys you the ability to move the address to another droplet.
       EC2     — associate an Elastic IP. The auto-assigned public IPv4 is
                 released on stop/start, so without this the address changes
                 under you and TLS renewal fails later, not now.

  2. Point DNS: an A record for $SITE_DOMAIN and www to that address.
     Confirm it resolves before step 4, or certbot burns a rate limit:

       dig +short $SITE_DOMAIN

  3. Open 80 and 443 at the provider's edge, if there is one.
       droplet — only applies if a cloud firewall is attached. If none is,
                 ufw above is already the whole firewall and this is a no-op.
       EC2     — required. The security group always applies, and a port that
                 is open in ufw but closed there is closed.

  4. Issue the certificate:

       certbot --apache -d $SITE_DOMAIN -d www.$SITE_DOMAIN

  5. Narrow SSH. 22 is open for recovery, not as the end state.
       droplet — restrict source to your own IP, or move to key-only plus
                 fail2ban, which is already running. Do not close 22 outright:
                 the recovery console in the control panel is a rescue path,
                 not a working admin channel, so leaving 22 reachable from
                 somewhere is the difference between locked down and locked out.
       EC2     — confirm the instance appears in Systems Manager first, then
                 remove the port 22 rule entirely. See the port 22 divergence
                 in AGENTS.md.

  6. Configure FluentSMTP. Outbound port 25 is blocked by default on both
     providers, so this needs a relay over 587/465 or an HTTP API rather than
     direct delivery. Until it is done, password resets and comment
     notifications fail silently — the site looks fine and the mail is gone.

  7. Set up backups at both layers, because they fail differently.
       droplet — enable droplet backups, or schedule snapshots.
       EC2     — EBS snapshots through Data Lifecycle Manager or AWS Backup.
     Neither provider backs anything up unless you turn it on. Then configure
     UpdraftPlus to off-site storage as the application-level backup, take one,
     and confirm it restores. A backup nobody has restored is not a backup.

  8. Activate the page cache only once the site is live:

       sudo -u www-data wp --path=$WP_DIR plugin activate wp-super-cache

EOF
