#!/usr/bin/env bash
#
# Provision an Ubuntu 24.04 host to serve The-abyss.
#
# This is the droplet-side mirror of docker/Dockerfile and docker/entrypoint.sh.
# The container was built by hand, one step at a time, so that this script could
# be written from something already proven rather than from a guess. Where the
# two differ, the difference is deliberate and commented.
#
# Retargeted to AWS EC2 on 2026-08-01. The stack is identical, because this was
# written against Ubuntu rather than against a provider. What changed is the
# platform around it: the login user, the firewall model, and swap. Those are
# marked EC2 below.
#
# EC2's Ubuntu AMI logs you in as `ubuntu` and disables root SSH, so this is run
# under sudo rather than as root directly:
#
#   # ON AWS SERVER
#   sudo SITE_DOMAIN=example.com SITE_TITLE='The-abyss' \
#        ADMIN_USER=casey ADMIN_EMAIL=you@example.com \
#        bash scripts/provision.sh
#
# Passwords are never arguments, never defaults, and never written to this file.
# The script prompts for them with a silent read, so they stay out of the shell
# history, out of the process list, and out of the repository. That is tier 0 in
# AGENTS.md and the reason wp-config.php is not generated by the container
# entrypoint either.
#
# Idempotent: safe to re-run. Every step checks for its own result first, so a
# re-run after a failure resumes rather than duplicating.

set -euo pipefail

SKIPS=0

# --- configuration ----------------------------------------------------------

SITE_DOMAIN="${SITE_DOMAIN:-}"
SITE_TITLE="${SITE_TITLE:-The-abyss}"
ADMIN_USER="${ADMIN_USER:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-}"

WP_DIR="/var/www/the-abyss"
DB_NAME="${DB_NAME:-theabyss}"
DB_USER="${DB_USER:-theabyss}"

# The repository, so the theme can be deployed from it. Defaults to the checkout
# this script is being run from.
REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

log()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }

# Is this a real host with an init system, or a container?
#
# The script has to run in both. A plain container has no systemd, no ufw that
# can load kernel modules, and no swap it is allowed to create, and PLAN.md
# already records that as the container's known limitation. Guarding these three
# is what lets the whole WordPress-shaped part of this script be tested in a
# throwaway container before it is ever pointed at an EC2 instance that costs
# money and takes a relaunch to fix.
#
# The guards skip; they never fake. A skipped step says so, loudly, so a
# container run is never mistaken for a full one.
has_systemd() { [ -d /run/systemd/system ]; }

# Start or restart a service through whichever mechanism exists.
svc() {
	if has_systemd; then
		systemctl "$1" "$2"
	else
		service "$2" "$1" >/dev/null 2>&1 || true
	fi
}
warn() { printf '\033[33mwarning: %s\033[0m\n' "$*" >&2; }
skipped() { printf '\033[33m   SKIPPED — %s\033[0m\n' "$*"; SKIPS=$((SKIPS+1)); }
die()  { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "must run as root. On EC2: sudo bash scripts/provision.sh"
[ -n "$SITE_DOMAIN" ] || die "SITE_DOMAIN is required, for example SITE_DOMAIN=example.com"
[ -n "$ADMIN_USER" ]  || die "ADMIN_USER is required."
[ -n "$ADMIN_EMAIL" ] || die "ADMIN_EMAIL is required."

# --- guard: do not clobber a site this script does not own -------------------
#
# This host has previously shared space with a live portfolio site. A provisioning
# script that silently disables another vhost, or overwrites another site's
# document root, is the single most damaging thing in this file. So it refuses
# rather than assumes.

if [ -e "$WP_DIR" ] && [ ! -e "$WP_DIR/wp-includes/version.php" ]; then
	die "$WP_DIR exists but is not a WordPress install. Refusing to touch it."
fi

for conf in /etc/apache2/sites-enabled/*.conf; do
	[ -e "$conf" ] || continue
	case "$(basename "$conf")" in
		the-abyss.conf|000-default.conf) continue ;;
	esac
	warn "another enabled vhost is present: $(basename "$conf")"
	warn "this script only adds the-abyss.conf and never disables anything else."
done

# --- packages ---------------------------------------------------------------
#
# The same list the Dockerfile installs. The PHP extensions are separate Debian
# packages, and a missing one surfaces as a blank 500 with nothing in the error
# log, because WordPress calls wp_die() rather than raising a PHP error. That
# cost a debugging session in the container; it is spelled out here so it cannot
# cost another one on the droplet.

log "Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq --no-install-recommends \
	ca-certificates curl less nano \
	apache2 \
	php-fpm php-mysql php-curl php-xml php-mbstring php-zip php-gd php-intl \
	mysql-server \
	certbot python3-certbot-apache \
	fail2ban \
	ufw

# --- apache -----------------------------------------------------------------

log "Configuring Apache"

# The FPM conf name carries the PHP version, which differs between Ubuntu
# releases. Discovering it is what keeps this script working across an upgrade.
FPM_CONF="$(basename "$(ls /etc/apache2/conf-available/php*-fpm.conf | head -n1)" .conf)"
[ -n "$FPM_CONF" ] || die "no php*-fpm.conf found; is php-fpm installed?"

a2enmod proxy_fcgi setenvif rewrite headers >/dev/null
a2enconf "$FPM_CONF" >/dev/null

# The vhost is the same file the container uses, with only ServerName changed —
# which is exactly the claim docker/the-abyss.conf makes about itself. Copying
# and substituting keeps that claim true instead of aspirational.
install -d "$WP_DIR"
sed "s/ServerName localhost/ServerName $SITE_DOMAIN\n    ServerAlias www.$SITE_DOMAIN/" \
	"$REPO_DIR/docker/the-abyss.conf" > /etc/apache2/sites-available/the-abyss.conf

a2ensite the-abyss >/dev/null
# 000-default answers on the same *:80 with no ServerName, so whichever loaded
# first wins and the Apache welcome page shows instead of the site.
a2dissite 000-default >/dev/null 2>&1 || true
apache2ctl configtest
svc reload apache2
svc start apache2

# --- wp-cli -----------------------------------------------------------------
#
# Official phar, not the Debian package, which lags badly. Same two lines as the
# Dockerfile.

if ! command -v wp >/dev/null; then
	log "Installing WP-CLI"
	curl -fsSL -o /usr/local/bin/wp \
		https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
	chmod +x /usr/local/bin/wp
	wp --allow-root --info >/dev/null
fi

wp_run() { sudo -u www-data -- wp --path="$WP_DIR" "$@"; }

# --- database ---------------------------------------------------------------

log "Database"

if mysql -N -B -e "SHOW DATABASES LIKE '$DB_NAME';" | grep -q "$DB_NAME"; then
	echo "database $DB_NAME already exists, leaving it alone"
	DB_PASS=""
else
	# Silent read. Never a script default, never an argument, so it stays out of
	# the process list and the shell history.
	read -rsp "New password for MySQL user '$DB_USER': " DB_PASS; echo
	[ -n "$DB_PASS" ] || die "database password cannot be empty."

	# utf8mb4 so emoji and non-Latin scripts survive. utf8 in MySQL is three
	# bytes and silently truncates at the first four-byte character.
	mysql -e "CREATE DATABASE \`$DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
	mysql -e "CREATE USER IF NOT EXISTS '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';"
	mysql -e "GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';"
	mysql -e "FLUSH PRIVILEGES;"
fi

# --- wordpress core ---------------------------------------------------------

log "WordPress core"

if [ ! -f "$WP_DIR/wp-includes/version.php" ]; then
	sudo -u www-data -- wp --path="$WP_DIR" core download
fi
chown -R www-data:www-data "$WP_DIR"

if [ ! -f "$WP_DIR/wp-config.php" ]; then
	[ -n "$DB_PASS" ] || die "wp-config.php is missing but the database already existed, so its password is not known here. Write wp-config.php by hand, or drop the database and re-run."

	# Salts come from the WordPress.org API, which wp config create calls itself.
	wp_run config create \
		--dbname="$DB_NAME" --dbuser="$DB_USER" --dbpass="$DB_PASS" \
		--dbcharset=utf8mb4 --dbcollate=utf8mb4_unicode_ci --skip-check

	# Pinned by constant rather than left in the database, so the site cannot be
	# half-migrated by an option row someone forgot. The container does the same
	# against http://localhost:8080.
	wp_run config set WP_HOME    "https://$SITE_DOMAIN" --type=constant
	wp_run config set WP_SITEURL "https://$SITE_DOMAIN" --type=constant

	# File edit from wp-admin is a code-execution path for any compromised admin
	# account, and this theme is deployed from Git rather than edited in place.
	wp_run config set DISALLOW_FILE_EDIT true --raw --type=constant
fi
unset DB_PASS

if ! wp_run core is-installed 2>/dev/null; then
	read -rsp "Password for the new WordPress admin '$ADMIN_USER': " ADMIN_PASS; echo
	[ -n "$ADMIN_PASS" ] || die "admin password cannot be empty."

	wp_run core install \
		--url="https://$SITE_DOMAIN" \
		--title="$SITE_TITLE" \
		--admin_user="$ADMIN_USER" \
		--admin_password="$ADMIN_PASS" \
		--admin_email="$ADMIN_EMAIL" \
		--skip-email
	unset ADMIN_PASS
fi

# Pretty permalinks. Requires AllowOverride All, which the vhost already sets;
# without it every URL except the home page 404s.
wp_run rewrite structure '/%category%/%postname%/' >/dev/null
wp_run rewrite flush --hard >/dev/null

# `wp rewrite flush --hard` writes the BEGIN/END WordPress markers but leaves
# them empty when it cannot detect Apache, which it cannot from the CLI. The
# result is a site where every URL except the home page 404s, with an .htaccess
# that looks correct at a glance because the markers are there. Observed locally
# 2026-08-01. Written explicitly rather than trusted.
if ! grep -q 'RewriteEngine On' "$WP_DIR/.htaccess" 2>/dev/null; then
	cat > "$WP_DIR/.htaccess" <<'HTACCESS'

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>
# END WordPress
HTACCESS
	chown www-data:www-data "$WP_DIR/.htaccess"
fi

# --- theme ------------------------------------------------------------------
#
# Deployed by symlink from the checkout, matching the container, so a git pull is
# the whole deploy and there is no copy step to forget.

log "Theme"
THEMES_DIR="$WP_DIR/wp-content/themes"
# Renamed 2026-08-01: the theme directory is abyss-theme, and the old `theme/`
# was deleted in the same change. Left as `the-abyss` this silently created a
# dangling symlink and then failed to activate a theme that no longer exists.
if [ ! -e "$THEMES_DIR/abyss-theme" ]; then
	ln -s "$REPO_DIR/abyss-theme" "$THEMES_DIR/abyss-theme"
fi
wp_run theme activate abyss-theme

# --- plugins ----------------------------------------------------------------
#
# Read from scripts/plugins.txt so this list exists in exactly one place.

log "Plugins"
# Read on fd 3, not stdin. `wp` inherits stdin and will happily consume the rest
# of the plugin list, so a plain `while read ... done < file` installs the first
# plugin and silently skips the others.
while read -r line <&3; do
	line="${line%%#*}"
	line="$(echo "$line" | xargs || true)"
	[ -n "$line" ] || continue

	slug="${line%%:*}"
	if [ "$line" = "${slug}:inactive" ]; then
		wp_run plugin is-installed "$slug" 2>/dev/null || wp_run plugin install "$slug"
	else
		wp_run plugin is-installed "$slug" 2>/dev/null || wp_run plugin install "$slug"
		wp_run plugin activate "$slug" >/dev/null
	fi
done 3< "$REPO_DIR/scripts/plugins.txt"

# --- hardening --------------------------------------------------------------

log "Swap"
# EC2 (and the smaller droplet sizes) ship with no swap. The architecture table
# in PLAN.md calls for 2 GiB at low swappiness: MySQL, PHP workers, and image
# processing sharing 2 GiB of RAM is exactly where a WordPress host OOMs, and
# the OOM killer usually takes MySQL, which looks like data corruption rather
# than memory pressure.
if ! has_systemd; then
	skipped "swap: containers cannot swapon; this runs on the real host only"
elif [ "$(swapon --show --noheadings | wc -l)" -eq 0 ] && [ ! -f /swapfile ]; then
	fallocate -l 2G /swapfile
	chmod 600 /swapfile
	mkswap /swapfile >/dev/null
	swapon /swapfile
	grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
	# Low, not zero. Swapping is a last resort here, not routine paging.
	sysctl -q -w vm.swappiness=10
	grep -q '^vm.swappiness' /etc/sysctl.conf || echo 'vm.swappiness=10' >> /etc/sysctl.conf
else
	echo "swap already present, leaving it alone"
fi

log "Firewall and fail2ban"
# EC2: the security group is the real firewall and is configured in AWS, not
# here. ufw is a second, host-level layer. It is enabled because defence in depth
# is worth having, but note that the two can disagree silently — a port open in
# the security group and closed here simply does not work, with nothing in either
# console saying why. Check both when a port appears dead.
#
# OpenSSH is allowed before enabling, which is the difference between a firewall
# and a lockout. On EC2 a lockout is recoverable only through SSM or a stop,
# detach, fix, reattach cycle, so the ordering here is load-bearing.
if has_systemd; then
	ufw allow OpenSSH >/dev/null
	ufw allow 'Apache Full' >/dev/null
	ufw --force enable >/dev/null
	systemctl enable --now fail2ban >/dev/null
else
	skipped "firewall and fail2ban: no init system; this runs on the real host only"
fi

# --- TLS --------------------------------------------------------------------
#
# Deliberately last, and deliberately not run. Certbot fails and burns a rate
# limit if DNS does not already resolve to this host, and pointing DNS is an
# outward-facing action that belongs to the human, not to a script.

log "Done"
cat <<EOF

Provisioned: https://$SITE_DOMAIN  (not yet TLS)

Remaining, in order, and yours to run:

  1. Associate an Elastic IP, if you have not already. An auto-assigned public
     IPv4 is released on stop/start, and both DNS and TLS need a stable address.

  2. Point DNS: an A record for $SITE_DOMAIN and www to that Elastic IP.
     Confirm it resolves before step 3, or certbot burns a rate limit:

       dig +short $SITE_DOMAIN

  3. Open 80 and 443 in the security group. ufw is already allowing them
     host-side, but the security group is the firewall that decides.

  4. Issue the certificate:

       certbot --apache -d $SITE_DOMAIN -d www.$SITE_DOMAIN

  5. Confirm the instance appears in Systems Manager, then remove the port 22
     rule from the security group. See the port 22 divergence in AGENTS.md:
     22 is open at launch for recovery, not as the end state.

  6. Configure FluentSMTP. Outbound port 25 is blocked on EC2, so this needs
     SES or another provider over 587/465 or an HTTP API. Until it is done,
     password resets and comment notifications fail silently.

  7. Configure EBS snapshots through Data Lifecycle Manager or AWS Backup.
     EC2 has no automatic backups; unless you set this up, there are none.
     Then configure UpdraftPlus to S3 as the application-level backup, take one,
     and confirm it restores. A backup nobody has restored is not a backup.

  8. Activate the page cache only once the site is live:

       sudo -u www-data wp --path=$WP_DIR plugin activate wp-super-cache

EOF
